### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by MJV-1988** [has2k1/scikit-misc#10]
Hi, I haven't been able to install scikit-misc on Windows 10. I found this [thread](https://github.com/has2k1/scikit-misc-wheels/issues/2) regarding scikit-misc-wheels, and it looked like it wasn't able to be run on Windows. 

Is that the case for scikit-misc? The error I was seeing suggested there was a problem compiling Fortran code.

**Comment by has2k1** [comment]
I cannot build wheels for Windows, so I depended on https://www.lfd.uci.edu/~gohlke/pythonlibs/ which only has wheels for python versions 3.5, 3.6 and 3.7. 

I recently came to know of [cibuildwheel](https://github.com/joerick/cibuildwheel/) that should make building wheels easier. That is the future of package `scikit-misc` and it should solve it for windows.

**Comment by MJV-1988** [comment]
No problem, thanks for the clarification.

**Comment by has2k1** [comment]
Reopened until issue is solved.

**Comment by cgohlke** [comment]
> https://www.lfd.uci.edu/~gohlke/pythonlibs/ which only has wheels for python versions 3.5, 3.6 and 3.7.

I updated the wheels at https://www.lfd.uci.edu/~gohlke/pythonlibs/#scikit-misc

**Comment by has2k1** [comment]
@MJV-1988 Issue has been resolved.

Thank you very much @cgohlke.
