### ISSUE TITLE
fail to install the package on Mac M1 Chip

### ISSUE THREAD

**Issue by jingshuw** [has2k1/scikit-misc#13]
I'm wondering if it's possible to make the package compactable with Mac M1 Chip. I can pip install the package, but I get the following error I import skmisc.loess:

>>> import skmisc.loess
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jingshuw/miniforge3/lib/python3.9/site-packages/skmisc/loess/__init__.py", line 51, in <module>
    from ._loess import (loess, loess_model, loess_inputs, loess_control,
ImportError: dlopen(/Users/jingshuw/miniforge3/lib/python3.9/site-packages/skmisc/loess/_loess.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/Users/jingshuw/miniforge3/lib/python3.9/site-packages/skmisc/loess/_loess.cpython-39-darwin.so: mach-o, but wrong architecture
	/Users/jingshuw/miniforge3/lib/python3.9/site-packages/skmisc/loess/_loess.cpython-39-darwin.so: mach-o, but wrong architecture

**Comment by has2k1** [comment]
M1 installation resolved.
