### ISSUE TITLE
Fail to install scikit-misc on Apple M1

### ISSUE THREAD

**Issue by watiss** [has2k1/scikit-misc#15]
Hi.

I am trying to install scikit-misc on an Apple M1 macbook. However I am not succeeding in doing so with pip install. I tried `conda install -c conda-forge scikit-misc` as instructed on [this](https://anaconda.org/conda-forge/scikit-misc) page. However this fails as well as the package is not being found on the available channels:
<img width="617" alt="Screen Shot 2022-06-02 at 10 14 00 AM" src="https://user-images.githubusercontent.com/4193454/171686566-5984e84a-1ceb-4b9d-aceb-df98a4dcb6a4.png">

I am using a conda environment using miniconda.

Are there no sciki-misc wheels/binaries available for osx-arm64? I only see osx-64 [here](https://anaconda.org/conda-forge/scikit-misc).

Thanks ahead.

**Comment by has2k1** [comment]
There are no binaries for arm64. I haven't been able to create them, most recent attempt is two days ago -> https://github.com/has2k1/scikit-misc-wheels/actions/runs/2416403685.

**Comment by watiss** [comment]
Does it mean scikit-misc cannot currently be installed on Apple M1 (without using rosetta)?

**Comment by has2k1** [comment]
> Does it mean scikit-misc cannot currently be installed on Apple M1 (without using rosetta)?

Yes.

**Comment by has2k1** [comment]
@watiss, can you try again using pip. I have uploaded binaries for python 3.9 & 3.10.

**Comment by watiss** [comment]
It works, thanks!
