### ISSUE TITLE
Running setup.py install for scikit-misc did not run successfully.

### ISSUE THREAD

**Issue by 17621802479** [has2k1/scikit-misc#16]
C:\Users\17621802479>pip install scikit-misc
Collecting scikit-misc
  Using cached scikit-misc-0.1.4.tar.gz (852 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in d:\python相关\python\lib\site-packages (from scikit-misc) (1.23.2)
Using legacy 'setup.py install' for scikit-misc, since package 'wheel' is not installed.
Installing collected packages: scikit-misc
  Running setup.py install for scikit-misc ... error
  error: subprocess-exited-with-error

  × Running setup.py install for scikit-misc did not run successfully.
  │ exit code: 1
  ╰─> [230 lines of output]
      C:\Users\17621802479\AppData\Local\Temp\pip-install-21mv2hsl\scikit-misc_357780ddc9f042a697af0739917fb7f7\setup.py:144: DeprecationWarning:

        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html

        from numpy.distutils.core import setup, numpy_cmdclass
      D:\python相关\python\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      WARNING: The wheel package is not available.
      INFO: blas_opt_info:
      INFO: blas_armpl_info:
      INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      INFO: customize MSVCCompiler
      INFO:   libraries armpl_lp64_mp not found in ['D:\\python相关\\python\\lib', 'C:\\', 'D:\\python相关\\python\\libs']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: blas_mkl_info:
      INFO:   libraries mkl_rt not found in ['D:\\python相关\\python\\lib', 'C:\\', 'D:\\python相关\\python\\libs']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: blis_info:
      INFO:   libraries blis not found in ['D:\\python相关\\python\\lib', 'C:\\', 'D:\\python相关\\python\\libs']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: openblas_info:
      INFO:   libraries openblas not found in ['D:\\python相关\\python\\lib', 'C:\\', 'D:\\python相关\\python\\libs']
      INFO: get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
      INFO: customize GnuFCompiler
      WARN: Could not locate executable g77
      WARN: Could not locate executable f77
      INFO: customize IntelVisualFCompiler
      WARN: Could not locate executable ifort
      WARN: Could not locate executable ifl
      INFO: customize AbsoftFCompiler
      WARN: Could not locate executable f90
      INFO: customize CompaqVisualFCompiler
      WARN: Could not locate executable DF
      INFO: customize IntelItaniumVisualFCompiler
      WARN: Could not locate executable efl
      INFO: customize Gnu95FCompiler
      WARN: Could not locate executable gfortran
      WARN: Could not locate executable f95
      INFO: customize G95FCompiler
      WARN: Could not locate executable g95
      INFO: customize IntelEM64VisualFCompiler
      INFO: customize IntelEM64TFCompiler
      WARN: Could not locate executable efort
      WARN: Could not locate executable efc
      INFO: customize PGroupFlangCompiler
      WARN: Could not locate executable flang
      WARN: don't know how to compile Fortran code on platform 'nt'
      INFO:   NOT AVAILABLE
      INFO:
      INFO: accelerate_info:
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_blas_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries tatlas not found in ['D:\\python相关\\python\\lib', 'C:\\', 'D:\\python相关\\python\\libs']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_blas_info:
      INFO:   libraries satlas not found in ['D:\\python相关\\python\\lib', 'C:\\', 'D:\\python相关\\python\\libs']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_blas_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries ptf77blas,ptcblas,atlas not found in ['D:\\python相关\\python\\lib', 'C:\\', 'D:\\python相关\\python\\libs']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_blas_info:
      INFO:   libraries f77blas,cblas,atlas not found in ['D:\\python相关\\python\\lib', 'C:\\', 'D:\\python相关\\python\\libs']
      INFO:   NOT AVAILABLE
      INFO:
      D:\python相关\python\lib\site-packages\numpy\distutils\system_info.py:2077: UserWarning:
          Optimized (vendor) Blas libraries are not found.
          Falls back to netlib Blas library which has worse performance.
          A better performance should be easily gained by switching
          Blas library.
        if self._calc_info(blas):
      INFO: blas_info:
      INFO:   libraries blas not found in ['D:\\python相关\\python\\lib', 'C:\\', 'D:\\python相关\\python\\libs']
      INFO:   NOT AVAILABLE
      INFO:
      D:\python相关\python\lib\site-packages\numpy\distutils\system_info.py:2077: UserWarning:
          Blas (http://www.netlib.org/blas/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [blas]) or by setting
          the BLAS environment variable.
        if self._calc_info(blas):
      INFO: blas_src_info:
      INFO:   NOT AVAILABLE
      INFO:
      D:\python相关\python\lib\site-packages\numpy\distutils\system_info.py:2077: UserWarning:
          Blas (http://www.netlib.org/blas/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [blas_src]) or by setting
          the BLAS_SRC environment variable.
        if self._calc_info(blas):
      INFO:   NOT AVAILABLE
      INFO:
      running install
      D:\python相关\python\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running config_cc
      INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      INFO: build_src
      INFO: building py_modules sources
      INFO: building library "floess" sources
      INFO: building extension "skmisc.loess._loess" sources
      INFO: building data_files sources
      INFO: build_src: building npy-pkg config files
      running build_py
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\skmisc
      copying skmisc\setup.py -> build\lib.win-amd64-cpython-310\skmisc
      copying skmisc\_version.py -> build\lib.win-amd64-cpython-310\skmisc
      copying skmisc\__config__.py -> build\lib.win-amd64-cpython-310\skmisc
      copying skmisc\__init__.py -> build\lib.win-amd64-cpython-310\skmisc
      copying build\src.win-amd64-3.10\skmisc\__config__.py -> build\lib.win-amd64-cpython-310\skmisc
      creating build\lib.win-amd64-cpython-310\skmisc\loess
      copying skmisc\loess\setup.py -> build\lib.win-amd64-cpython-310\skmisc\loess
      copying skmisc\loess\__init__.py -> build\lib.win-amd64-cpython-310\skmisc\loess
      creating build\lib.win-amd64-cpython-310\skmisc\loess\tests
      copying skmisc\loess\tests\test_loess.py -> build\lib.win-amd64-cpython-310\skmisc\loess\tests
      copying skmisc\loess\tests\__init__.py -> build\lib.win-amd64-cpython-310\skmisc\loess\tests
      UPDATING build\lib.win-amd64-cpython-310\skmisc/_version.py
      set build\lib.win-amd64-cpython-310\skmisc/_version.py to '0.1.4'
      running build_clib
      INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      INFO: customize MSVCCompiler
      INFO: customize MSVCCompiler using build_clib
      INFO: CCompilerOpt.cc_test_flags[1073] : testing flags (/O2)
      creating C:\Users\176218~1\AppData\Local\Temp\tmpzcrd2haj\python相关
      creating C:\Users\176218~1\AppData\Local\Temp\tmpzcrd2haj\python相关\python
      creating C:\Users\176218~1\AppData\Local\Temp\tmpzcrd2haj\python相关\python\Lib
      creating C:\Users\176218~1\AppData\Local\Temp\tmpzcrd2haj\python相关\python\Lib\site-packages
      creating C:\Users\176218~1\AppData\Local\Temp\tmpzcrd2haj\python相关\python\Lib\site-packages\numpy
      creating C:\Users\176218~1\AppData\Local\Temp\tmpzcrd2haj\python相关\python\Lib\site-packages\numpy\distutils
      creating C:\Users\176218~1\AppData\Local\Temp\tmpzcrd2haj\python相关\python\Lib\site-packages\numpy\distutils\checks
      INFO: CCompilerOpt.cc_test_flags[1073] : testing flags (/WX)
      WARN: CCompilerOpt.__init__[1240] : feature 'AVX512_KNL' is disabled, MSVC compiler doesn't support it
      WARN: CCompilerOpt.__init__[1240] : feature 'AVX512_KNM' is disabled, MSVC compiler doesn't support it
      INFO: CCompilerOpt.__init__[1782] : check requested baseline
      INFO: CCompilerOpt.feature_test[1547] : testing feature 'SSE' with flags ()
      INFO: CCompilerOpt.feature_test[1547] : testing feature 'SSE2' with flags ()
      INFO: CCompilerOpt.feature_test[1547] : testing feature 'SSE3' with flags ()
      INFO: CCompilerOpt.__init__[1791] : check requested dispatch-able features
      INFO: CCompilerOpt.feature_test[1547] : testing feature 'SSE41' with flags ()
      INFO: CCompilerOpt.feature_test[1547] : testing feature 'POPCNT' with flags ()
      INFO: CCompilerOpt.feature_test[1547] : testing feature 'SSSE3' with flags ()
      INFO: CCompilerOpt.feature_test[1547] : testing feature 'SSE42' with flags ()
      INFO: CCompilerOpt.cc_test_flags[1073] : testing flags (/arch:AVX)
      INFO: CCompilerOpt.feature_test[1547] : testing feature 'AVX' with flags (/arch:AVX)
      INFO: CCompilerOpt.feature_test[1547] : testing feature 'F16C' with flags (/arch:AVX)
      INFO: CCompilerOpt.cc_test_flags[1073] : testing flags (/arch:AVX2)
      INFO: CCompilerOpt.feature_test[1547] : testing feature 'AVX2' with flags (/arch:AVX2)
      INFO: CCompilerOpt.feature_test[1547] : testing feature 'FMA3' with flags (/arch:AVX2)
      INFO: CCompilerOpt.cc_test_flags[1073] : testing flags (/arch:AVX512)
      INFO: CCompilerOpt.feature_test[1547] : testing feature 'AVX512_SKX' with flags (/arch:AVX512)
      INFO: CCompilerOpt.feature_test[1547] : testing feature 'AVX512_CNL' with flags (/arch:AVX512)
      INFO: CCompilerOpt.feature_test[1547] : testing feature 'AVX512CD' with flags (/arch:AVX512)
      INFO: CCompilerOpt.feature_test[1547] : testing feature 'AVX512_CLX' with flags (/arch:AVX512)
      INFO: CCompilerOpt.feature_test[1547] : testing feature 'AVX512F' with flags (/arch:AVX512)
      INFO: CCompilerOpt.feature_test[1547] : testing feature 'AVX512_ICL' with flags (/arch:AVX512)
      WARN: CCompilerOpt.dist_test[630] : CCompilerOpt._dist_test_spawn[764] : Command (D:\Visual Studio 2017\vs2017\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -ID:\Visual Studio 2017\vs2017\VC\Tools\MSVC\14.16.27023\ATLMFC\include -ID:\Visual Studio 2017\vs2017\VC\Tools\MSVC\14.16.27023\include -ID:\Windows Kits\10\include\10.0.17763.0\ucrt -ID:\Windows Kits\10\include\10.0.17763.0\shared -ID:\Windows Kits\10\include\10.0.17763.0\um -ID:\Windows Kits\10\include\10.0.17763.0\winrt -ID:\Windows Kits\10\include\10.0.17763.0\cppwinrt /TcD:\python相关\python\Lib\site-packages\numpy\distutils\checks\cpu_avx512_icl.c /FoC:\Users\176218~1\AppData\Local\Temp\tmpzcrd2haj\python 相关\python\Lib\site-packages\numpy\distutils\checks\cpu_avx512_icl.obj /arch:AVX512 /WX) failed with exit status 2 output ->
      cpu_avx512_icl.c
      D:\python相关\python\Lib\site-packages\numpy\distutils\checks\cpu_avx512_icl.c(20): error C2220: 警告被视为错误 - 没有生成“object”文件
      D:\python相关\python\Lib\site-packages\numpy\distutils\checks\cpu_avx512_icl.c(20): warning C4013: “_mm512_shrdv_epi64”未定义；假设外部返回 int
      D:\python相关\python\Lib\site-packages\numpy\distutils\checks\cpu_avx512_icl.c(20): error C2440: “=”: 无法从“int”转换为“__m512i”
      D:\python相关\python\Lib\site-packages\numpy\distutils\checks\cpu_avx512_icl.c(22): warning C4013: “_mm512_popcnt_epi8”未定义；假设外部返回 int
      D:\python相关\python\Lib\site-packages\numpy\distutils\checks\cpu_avx512_icl.c(22): error C2440: “=”: 无法从“int”转换为“__m512i”
      D:\python相关\python\Lib\site-packages\numpy\distutils\checks\cpu_avx512_icl.c(24): warning C4013: “_mm512_popcnt_epi64”未定义；假设外部返回 int
      D:\python相关\python\Lib\site-packages\numpy\distutils\checks\cpu_avx512_icl.c(24): error C2440: “=”: 无法从“int”转换为“__m512i”

      WARN: CCompilerOpt.feature_test[1563] : testing failed
      INFO: CCompilerOpt.__init__[1803] : skip features (SSE2 SSE3 SSE) since its part of baseline
      INFO: CCompilerOpt.__init__[1807] : initialize targets groups
      INFO: CCompilerOpt.__init__[1809] : parse target group simd_test
      INFO: CCompilerOpt._parse_target_tokens[2020] : skip targets (VXE VSX4 VXE2 ASIMD VSX2 VSX FMA4 XOP NEON VX VSX3) not part of baseline or dispatch-able features
      INFO: CCompilerOpt._parse_policy_not_keepbase[2132] : skip baseline features (SSE2)
      INFO: CCompilerOpt.generate_dispatch_header[2353] : generate CPU dispatch header: (build\src.win-amd64-3.10\numpy\distutils\include\npy_cpu_dispatch_config.h)
      WARN: CCompilerOpt.generate_dispatch_header[2362] : dispatch header dir build\src.win-amd64-3.10\numpy\distutils\include does not exist, creating it
      INFO: CCompilerOpt.feature_extra_checks[1627] : Testing extra checks for feature 'AVX512F' (AVX512F_REDUCE)
      INFO: CCompilerOpt.feature_extra_checks[1627] : Testing extra checks for feature 'AVX512_SKX' (AVX512BW_MASK AVX512DQ_MASK)
      WARN: CCompilerOpt.dist_test[630] : CCompilerOpt._dist_test_spawn[764] : Command (D:\Visual Studio 2017\vs2017\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -ID:\Visual Studio 2017\vs2017\VC\Tools\MSVC\14.16.27023\ATLMFC\include -ID:\Visual Studio 2017\vs2017\VC\Tools\MSVC\14.16.27023\include -ID:\Windows Kits\10\include\10.0.17763.0\ucrt -ID:\Windows Kits\10\include\10.0.17763.0\shared -ID:\Windows Kits\10\include\10.0.17763.0\um -ID:\Windows Kits\10\include\10.0.17763.0\winrt -ID:\Windows Kits\10\include\10.0.17763.0\cppwinrt /TcD:\python相关\python\Lib\site-packages\numpy\distutils\checks\extra_avx512bw_mask.c /FoC:\Users\176218~1\AppData\Local\Temp\tmpzcrd2haj\python相关\python\Lib\site-packages\numpy\distutils\checks\extra_avx512bw_mask.obj /arch:AVX512 /WX) failed with exit status 2 output ->
      extra_avx512bw_mask.c
      D:\python相关\python\Lib\site-packages\numpy\distutils\checks\extra_avx512bw_mask.c(12): error C2220: 警告被视为错误 - 没有生成“object”文件
      D:\python相关\python\Lib\site-packages\numpy\distutils\checks\extra_avx512bw_mask.c(12): warning C4013: “_kor_mask64”未定义；假设外部返回 int
      D:\python相关\python\Lib\site-packages\numpy\distutils\checks\extra_avx512bw_mask.c(13): warning C4013: “_kxor_mask64”未定义；假设外部返回 int
      D:\python相关\python\Lib\site-packages\numpy\distutils\checks\extra_avx512bw_mask.c(14): warning C4013: “_cvtu64_mask64”未定义；假设外部返回 int
      D:\python相关\python\Lib\site-packages\numpy\distutils\checks\extra_avx512bw_mask.c(14): warning C4013: “_cvtmask64_u64”未定义；假设外部返回 int

      WARN: CCompilerOpt.dist_test[630] : CCompilerOpt._dist_test_spawn[764] : Command (D:\Visual Studio 2017\vs2017\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -ID:\Visual Studio 2017\vs2017\VC\Tools\MSVC\14.16.27023\ATLMFC\include -ID:\Visual Studio 2017\vs2017\VC\Tools\MSVC\14.16.27023\include -ID:\Windows Kits\10\include\10.0.17763.0\ucrt -ID:\Windows Kits\10\include\10.0.17763.0\shared -ID:\Windows Kits\10\include\10.0.17763.0\um -ID:\Windows Kits\10\include\10.0.17763.0\winrt -ID:\Windows Kits\10\include\10.0.17763.0\cppwinrt /TcD:\python相关\python\Lib\site-packages\numpy\distutils\checks\extra_avx512dq_mask.c /FoC:\Users\176218~1\AppData\Local\Temp\tmpzcrd2haj\python相关\python\Lib\site-packages\numpy\distutils\checks\extra_avx512dq_mask.obj /arch:AVX512 /WX) failed with exit status 2 output ->
      extra_avx512dq_mask.c
      D:\python相关\python\Lib\site-packages\numpy\distutils\checks\extra_avx512dq_mask.c(12): error C2220: 警告被视为错误 - 没有生成“object”文件
      D:\python相关\python\Lib\site-packages\numpy\distutils\checks\extra_avx512dq_mask.c(12): warning C4013: “_kor_mask8”未定义；假设外部返回 int
      D:\python相关\python\Lib\site-packages\numpy\distutils\checks\extra_avx512dq_mask.c(13): warning C4013: “_kxor_mask8”未定义；假设外部返回 int
      D:\python相关\python\Lib\site-packages\numpy\distutils\checks\extra_avx512dq_mask.c(14): warning C4013: “_cvtu32_mask8”未定义；假设外部返回 int
      D:\python相关\python\Lib\site-packages\numpy\distutils\checks\extra_avx512dq_mask.c(14): warning C4013: “_cvtmask8_u32”未定义；假设外部返回 int

      WARN: CCompilerOpt.feature_extra_checks[1645] : testing failed for checks (AVX512BW_MASK AVX512DQ_MASK)
      INFO: building 'floess' library
      error: library floess has Fortran sources but no Fortran compiler found
      INFO:
      ########### CLIB COMPILER OPTIMIZATION ###########
      INFO: Platform      :
        Architecture: x64
        Compiler    : msvc

      CPU baseline  :
        Requested   : 'min'
        Enabled     : SSE SSE2 SSE3
        Flags       : none
        Extra checks: none

      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL
        Generated   : none
      INFO: CCompilerOpt.cache_flush[857] : write cache to path -> C:\Users\17621802479\AppData\Local\Temp\pip-install-21mv2hsl\scikit-misc_357780ddc9f042a697af0739917fb7f7\build\temp.win-amd64-cpython-310\ccompiler_opt_cache_clib.py
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> scikit-misc

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by 17621802479** [comment]
who can help me ?

**Comment by Shelly-S** [comment]
Seems you are using py310 on Win, py37/py38/py39 might work. And could you please list the versions of your packages? 
[Reference](https://pypi.org/project/scikit-misc/#files)

**Comment by has2k1** [comment]
Closing as the way the package is built has changed and binary wheels will be available for windows.
