### ISSUE TITLE
Question regarding numpy

### ISSUE THREAD

**Issue by penguinpee** [has2k1/scikit-misc#24]
`skmisc/meson.build` [mentions](https://github.com/has2k1/scikit-misc/blob/8f829888ecf0fa96eb18aeb3f723fc985de5abcd/skmisc/meson.build#L26):

```python
# Note: `required: false` can be removed once numpy 1.19 is the minimum version
npyrandom_lib = cc.find_library('npyrandom', dirs: npyrandom_path, required: false)
```

In [`pyprojecttoml`](https://github.com/has2k1/scikit-misc/blob/8f829888ecf0fa96eb18aeb3f723fc985de5abcd/pyproject.toml#L13) the `numpy` dependency is defined as:

```python
    "numpy>=1.22.3",
```

So, I guess the `required: false` can be dropped?

**Comment by has2k1** [comment]
I guess it can be dropped.

During the testing period I had [1.19](https://github.com/has2k1/scikit-misc/blob/v0.2.0rc1/pyproject.toml#L14) as the minimum version. Some issues popped up and I bumped it to `1.22.3`. In the end, I think bumping the version was not required, but I did not undo it!

**Comment by has2k1** [comment]
Resolved in the current version.
