### ISSUE TITLE
Missing wheels for MacOS/ARM for 0.4.0

### ISSUE THREAD

**Issue by ebezzi** [has2k1/scikit-misc#37]
Hello,

it looks like the wheel files for MacOS (ARM) aren't available for the [0.4.0 release](https://pypi.org/project/scikit-misc/0.4.0/#files), while they were for the [previous one](https://pypi.org/project/scikit-misc/0.3.1/#files). Is this intentional? This is causing some CI actions to fail on our repo (see [this](https://github.com/chanzuckerberg/cellxgene-census/actions/runs/9652844429/job/26623857587), for example), as it's now trying to build from source and I think we're missing some prerequisites for that.

Thanks!

**Comment by eroell** [comment]
This can also cause some troubles when working on a Mac, where the additional dependencies might not have been installed already and now suddenly need to be...

**Comment by has2k1** [comment]
I'm working on this. Given the languages (fortan (plus blas & lapack), c, cython + numpyapi, python) we mimic the build system config used by numpy and scipy. But numpy and scipy changed how they bundle openblas and that made it unfeasible for a project this small to do the same.

Nonetheless, we have a solution.

**Comment by has2k1** [comment]
Released in v0.5.0.
