### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by AndreKkl** [has2k1/scikit-misc#4]
Hi, 
I'm on windows and using a pipenv environment. 
The installation with pipenv install was successful and everythink is located in the X:\Users\XYZ\.virtualenvs\meret-LhVWc3ru\Lib\site-packages\skmisc\loess 
However, an error occured and i have no idea how to solve it:
```
File "X:\Users\XYZ\.virtualenvs\meret-LhVWc3ru\lib\site-packages\skmisc\loess\__init__.py", line 51, in <module>
    from ._loess import (loess, loess_model, loess_inputs, loess_control,
ImportError: DLL load failed: The specified module could not be found.
```

I tried to include the location "site-packages\skmisc\loess\_loess.cp36-win_amd64.pyd" to the windows path variable but no success. Why is this file not found by python?

**Comment by Fraser-Paine** [comment]
Having the same issue on a VM but not on my local machine. 
Any solution to this yet?

**Comment by has2k1** [comment]
Do other libraries like scipy, sklearn work?

**Comment by Fraser-Paine** [comment]
Yes, sklearn definitely works, haven't had a reason to use scipy yet but I could test it. 
Does this package require a VS C++ runtime to run? I haven't set one up in the Azure function environment but I do have it in the other envs which work.
I've also tried installing from a .whl from https://www.lfd.uci.edu/~gohlke/pythonlibs/#scikit-misc as I thought that might help but there was no change.

**Comment by cgohlke** [comment]
The wheels from https://www.lfd.uci.edu/~gohlke/pythonlibs/#scikit-misc require [numpy+mkl](https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy).

**Comment by has2k1** [comment]
@Fraser-Paine

> I've also tried installing from a .whl from https://www.lfd.uci.edu/~gohlke/pythonlibs/#scikit-misc as I thought that might help but there was no change.

Those are the same type of wheels that are on pypi. Can you try installing  [numpy+mkl](https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy) before any other packages.

**Comment by Fraser-Paine** [comment]
This totally fixed the issue for me. 
Thank you very much!

**Comment by has2k1** [comment]
Closing since the way the package is built has changed and binary wheels will be available for windows.
