### ISSUE TITLE
ValueError: b'Extrapolation not allowed with blending'

### ISSUE THREAD

**Issue by javierrodenas** [has2k1/scikit-misc#6]
Hi,

I am trying to predict the values in a sequence of days. I have fit my models with a range of days {day: 0 -> day: 50} and I would like to predict the day 51. 

When I try to do it, it appears the following error:

_ValueError: b'Extrapolation not allowed with blending'_

Is there any way to predict using  X that it has never seen before?

Thank you in davance

**Comment by has2k1** [comment]
As you have not posted any code I cannot tell how you have used the package, but find a way to set `surface='direct'`.

**Comment by javierrodenas** [comment]
Hi,

here is the code:

```
from skmisc.loess import loess

lo = loess(X, y_log, span=0.1)
lo.fit()

days_to_predict = [51]
prediction = lo.predict(X)

plt.scatter(X, y_log, color='red', label="Original Data")
plt.plot(X, prediction.values, color='blue', label="Predicted")
plt.show()
```
The package is **skmisc.loess** but as I posted last time, it only predicts numbers that are in range (has already seen) but no numbers that it has never seen before....

**Comment by has2k1** [comment]
The solution is

```python
lo = loess(X, y_log, span=0.1, surface='direct')
```

See the documentation at [loess_control](https://has2k1.github.io/scikit-misc/generated/skmisc.loess.loess_control.html#skmisc.loess.loess_control).

**Comment by javierrodenas** [comment]
Hi @has2k1,

Thank you very much, it worked! 

I am going to close the issue.
